extends:
  - plugin:@typescript-eslint/recommended
  - prettier
plugins:
  - jest
  - "@typescript-eslint"
  - prettier
env:
  commonjs: true
  es2020: true
  jest/globals: true
  node: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  prettier/prettier: error
  '@typescript-eslint/no-var-requires': 'off'
